/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/l3JpUHuEuEc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

const ConnorGustafson = () => {
  return (
    <div className="flex items-center p-6 bg-white shadow-lg rounded-lg max-w-4xl mx-auto">
      <Avatar className="w-24 h-24 mr-6">
        <AvatarImage src="https://nocodeconsulting.blob.core.windows.net/nocodeconsulting/connor%20gustafson.png" />
        <AvatarFallback>CG</AvatarFallback>
      </Avatar>
      <div className="flex flex-col flex-grow">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-semibold">Connor Gustafson</h2>
            <p className="text-lg text-gray-500">CEO</p>
          </div>
          <Badge variant="secondary" className="text-sm px-4 py-2">
            NoCode Consulting
          </Badge>
        </div>
        <div className="mt-4">
          <p className="font-semibold text-gray-700">Software designed for speed and scale.</p>
          <p className="text-gray-600">
            Build user-interfaces, SaaS apps, internal tools and automation better and faster with no-code.
          </p>
        </div>
        <div className="mt-4">
          <Button className="text-white">Get Started</Button>
        </div>
      </div>
    </div>
  )
}

export default ConnorGustafson;
