/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4tGc7dFB9Al
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function homePage() {
  return (
    <div className="bg-black text-white">
      <nav className="px-8 py-4 flex justify-between items-center">
        <div className="text-2xl font-bold">NoCode Consulting</div>
        <div className="space-x-4">
          <Link className="hover:underline" href="#">
            Company
          </Link>
          <Link className="hover:underline" href="#">
            Templates
          </Link>
          <Link className="hover:underline" href="#">
            Reviews
          </Link>
          <Select>
            <SelectTrigger aria-label="Learn" id="learn">
              <SelectValue placeholder="Learn" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="blog">Blog</SelectItem>
              <SelectItem value="faq">FAQ</SelectItem>
            </SelectContent>
          </Select>
          <Button className="text-white border-white hover:bg-white hover:text-black" variant="outline">
            Schedule 1-Hour
          </Button>
          <Button className="bg-purple-600 hover:bg-purple-700" variant="secondary">
            Login
          </Button>
        </div>
      </nav>
      <header className="px-8 py-16">
        <div className="max-w-3xl">
          <Badge className="mb-6" variant="secondary">
            No-Code Development Agency
          </Badge>
          <h1 className="text-5xl font-bold mb-6">Build enterprise software without writing code.</h1>
          <p className="text-xl mb-6">We help companies build apps and automate work with no-code software.</p>
          <div className="flex space-x-4">
            <Button>Get Started</Button>
            <Button className="text-white border-white hover:bg-white hover:text-black" variant="outline">
              Schedule 1-Hour
            </Button>
          </div>
        </div>
      </header>
      <section className="px-8 py-16">
        <h2 className="text-3xl font-bold mb-8">Company partners</h2>
        <div className="flex justify-between space-x-4 mb-16">
          <img
            alt="Airtable logo"
            className="h-10"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Zapier logo"
            className="h-10"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Softr logo"
            className="h-10"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Stacker logo"
            className="h-10"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Noloco logo"
            className="h-10"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="FlutterFlow logo"
            className="h-10"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100"
          />
        </div>
        <div className="flex items-center">
          <Avatar>
            <AvatarImage alt="CEO's Profile" src="/placeholder.svg?width=100&height=100" />
            <AvatarFallback>CG</AvatarFallback>
          </Avatar>
          <div className="ml-4">
            <div className="text-base font-semibold">Connor Gustafson</div>
            <div className="text-sm">CEO</div>
            <p className="text-sm my-2">
              Software designed for speed and scale. Build user-interfaces, SaaS apps, internal tools and automation
              better and faster with no-code.
            </p>
            <Button className="bg-[#bd1e59]" variant="secondary">
              Get Started
            </Button>
          </div>
        </div>
      </section>
      <footer className="px-8 py-4 text-center">
        <div className="text-xl font-bold">NoCode Consulting</div>
      </footer>
    </div>
  )
}
