/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Vgh4qBIPDJG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"

export default function Options() {
  return (
    <main className="p-4 space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <Card>
          <CardHeader>
            <div className="flex items-center space-x-2">
              <LaptopIcon className="w-6 h-6 text-blue-500" />
              <CardTitle>Private Consulting Hour</CardTitle>
            </div>
            <CardDescription>1-hour private consulting call</CardDescription>
          </CardHeader>
          <CardFooter>
            <Button variant="outline">Schedule 1-Hour →</Button>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <div className="flex items-center space-x-2">
              <CloudLightningIcon className="w-6 h-6 text-yellow-500" />
              <CardTitle>Expert Development Services</CardTitle>
            </div>
            <CardDescription>15-hour development sprints</CardDescription>
          </CardHeader>
          <CardFooter>
            <Button variant="outline">Get Started →</Button>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <div className="flex items-center space-x-2">
              <BoxIcon className="w-6 h-6 text-green-500" />
              <CardTitle>Template Library</CardTitle>
            </div>
            <CardDescription>Explore our template library</CardDescription>
          </CardHeader>
          <CardFooter>
            <Button variant="outline">Explore →</Button>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <div className="flex items-center space-x-2">
              <PlayIcon className="w-6 h-6 text-red-500" />
              <CardTitle>View Recordings</CardTitle>
            </div>
            <CardDescription>View your private recordings</CardDescription>
          </CardHeader>
          <CardFooter>
            <Button variant="outline">View →</Button>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <div className="flex items-center space-x-2">
              <PackageIcon className="w-6 h-6 text-purple-500" />
              <CardTitle>View Assets</CardTitle>
            </div>
            <CardDescription>View your project assets</CardDescription>
          </CardHeader>
          <CardFooter>
            <Button variant="outline">View →</Button>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <div className="flex items-center space-x-2">
              <UserIcon className="w-6 h-6 text-orange-500" />
              <CardTitle>My Account</CardTitle>
            </div>
            <CardDescription>Manage your account</CardDescription>
          </CardHeader>
          <CardFooter>
            <Button variant="outline">Manage →</Button>
          </CardFooter>
        </Card>
      </div>
    </main>
  )
}

function BoxIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}


function CloudLightningIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 16.326A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 .5 8.973" />
      <path d="m13 12-3 5h4l-3 5" />
    </svg>
  )
}


function LaptopIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16" />
    </svg>
  )
}


function PackageIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m7.5 4.27 9 5.15" />
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}


function PlayIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  )
}


function UserIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
